# Staging environment overrides
nodeSelector:
  feature.node.kubernetes.io/cpu-security.sev: "true"
  environment: staging

runtimeClass:
  name: kata-cc-staging
  handler: kata-qemu-sev
  scheduling:
    nodeSelector:
      feature.node.kubernetes.io/cpu-security.sev: "true"
      environment: staging

kataConfig:
  confidential_guest: true
  sev_guest: true
  default_vcpus: 2
  default_memory: 2048

configMap:
  data:
    KATA_HYPERVISOR: "qemu"
    KATA_CONFIDENTIAL: "true"
    SEV_ENABLED: "true"
    LOG_LEVEL: "info"
