apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inference.fullname" . }}
  labels:
    {{- include "inference.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
