apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "core-services.fullname" . }}
  labels:
    {{- include "core-services.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
