apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rl-training.fullname" . }}
  labels:
    {{- include "rl-training.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
