apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rl-training.fullname" . }}
  labels:
    {{- include "rl-training.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
