{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tee-runtime.fullname" . }}
  labels:
    {{- include "tee-runtime.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tee-runtime.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tee-runtime.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
