apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: {{ .Values.runtimeClass.name }}
  labels:
    {{- include "tee-runtime.labels" . | nindent 4 }}
handler: {{ .Values.runtimeClass.handler }}
{{- if .Values.runtimeClass.scheduling }}
scheduling:
  {{- with .Values.runtimeClass.scheduling.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.runtimeClass.scheduling.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
